#!/bin/sh

#Python 2018_01_12_SelectionDansDesTextGrids.py "*tuvois" 
#Python 2018_01_12_SelectionDansDesTextGrids.py "*style"
#Python 2018_01_12_SelectionDansDesTextGrids.py "*putain"
#Python 2018_01_12_SelectionDansDesTextGrids.py "*genre"
#Python 2018_01_12_SelectionDansDesTextGrids.py "*bluff"
#Python 2018_01_12_SelectionDansDesTextGrids.py "*wesh"
#Python 2018_01_12_SelectionDansDesTextGrids.py "*zaama"

#Python 2018_01_25_SelectionDansDesTextGrids2.py "*ne"
#Python 2018_01_25_SelectionDansDesTextGrids.py "non"

#Python 2018_01_25_SelectionDansDesTextGrids2.py "*ne"


#Python 2018_01_25_SelectionDansDesTextGrids2.py "*vasy"

#Python 2018_01_25_SelectionDansDesTextGrids2.py "*mere" 
#Python 2018_01_25_SelectionDansDesTextGrids2.py "fliper"
#Python 2018_01_25_SelectionDansDesTextGrids2.py "flipper"
#Python 2018_01_25_SelectionDansDesTextGrids2.py "flipper@s"
#Python 2018_01_25_SelectionDansDesTextGrids2.py "buter"
#Python 2018_01_25_SelectionDansDesTextGrids2.py "buter@s"
#Python 2018_01_25_SelectionDansDesTextGrids2.py "merde"
#Python 2018_01_25_SelectionDansDesTextGrids2.py "merde@s"
#Python 2018_01_25_SelectionDansDesTextGrids2.py "négro"
#Python 2018_01_25_SelectionDansDesTextGrids2.py "négro@s"       

#Python 2018_06_06_SelectionDansDesTextGrids2.py "*comme"        
#Python SelectionDansDesTextGrids.py "*etTout"   
#Python SelectionDansDesTextGrids.py "*ou comme ça"        
#Python SelectionDansDesTextGrids.py "quant à"
#Python SelectionDansDesTextGrids.py "d'autre part"
#Python SelectionDansDesTextGrids.py "d'ailleurs"
#Python SelectionDansDesTextGrids.py "en matière de"
#Python SelectionDansDesTextGrids.py "sur le plan"
#Python SelectionDansDesTextGrids.py "au plan"
#Python SelectionDansDesTextGrids.py "tandis que"        
# Python SelectionDansDesTextGrids.py "bien que"
# Python SelectionDansDesTextGrids.py "sur le plan"
#Python SelectionDansDesTextGrids.py "*crari"
#Python SelectionDansDesTextGrids.py "*bluff"
#Python SelectionDansDesTextGrids.py "genre"
#Python SelectionDansDesTextGrids.py "&="
#Python SelectionDansDesTextGrids.py "taro"
#Python SelectionDansDesTextGrids.py "nous*"
#Python SelectionDansDesTextGrids.py "lon "
#Python SelectionDansDesTextGrids.py "nouson*"
Python SelectionDansDesTextGrids.py "costard"
#Python SelectionDansDesTextGrids.py "maltraitent"